name: Set up Node.js
description: Install Node.js and dependencies

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version-file: .node-version

    - name: Set up pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      with:
        cache: true
        cache_dependency_path: hack/js/pnpm-lock.yaml
        package_json_file: hack/js/package.json
        run_install: |
          cwd: hack/js
