name: Set up Node.js
description: Install Node.js and dependencies

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
      with:
        cache: true
        cache-dependency-path: hack/js/pnpm-lock.yaml
        working-directory: hack/js
