name: Set up Node.js
description: Install Node.js and dependencies

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
      with:
        cache: true
        cache-dependency-path: hack/js/pnpm-lock.yaml
        working-directory: hack/js
