name: Lint actions
description: Lint GitHub Actions workflows and actions

inputs:
  advanced-security:
    description: Enable GitHub Advanced Security for zizmor's results?
    required: false
    default: "true"

runs:
  using: composite

  steps:
    - name: Install tools
      uses: $/install-tools
      with:
        tools: |-
          actionlint
          shellcheck

    - name: Run actionlint
      run: actionlint
      shell: bash

    - name: Run zizmor
      uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
      with:
        advanced-security: ${{ inputs.advanced-security }}
        annotations: ${{ inputs.advanced-security != 'true' }}
