name: Lint actions
description: Lint GitHub Actions workflows and actions

inputs:
  advanced-security:
    description: Enable GitHub Advanced Security for zizmor's results?
    required: false
    default: "true"

runs:
  using: composite

  steps:
    - name: Install tools
      uses: cerbos/actions/install-tools@cefe7f8508192b6e0a264933ca86f4b35bcd8415
      with:
        tools: |-
          actionlint
          shellcheck

    - name: Run actionlint
      run: actionlint
      shell: bash

    - name: Run zizmor
      uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
      with:
        advanced-security: ${{ inputs.advanced-security }}
        annotations: ${{ inputs.advanced-security != 'true' }}
