name: Lint actions
description: Lint GitHub Actions workflows and actions

inputs:
  advanced-security:
    description: Enable GitHub Advanced Security for zizmor's results?
    required: false
    default: "true"

runs:
  using: composite

  steps:
    - name: Install tools
      uses: cerbos/actions/install-tools@e17cf3db5462936b944f29fab88447ea556ffbd1
      with:
        tools: |-
          actionlint
          shellcheck

    - name: Run actionlint
      run: actionlint
      shell: bash

    - name: Run zizmor
      uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
      with:
        advanced-security: ${{ inputs.advanced-security }}
        annotations: ${{ inputs.advanced-security != 'true' }}
