name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  actions-install-tools:
    name: Test install-tools action
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: List tools
        id: toolbox
        run: jq --raw-output '["tools<<EOF"] + keys + ["EOF"] | .[]' < toolbox.json >> "${GITHUB_OUTPUT}"

      - name: Run
        uses: ./install-tools
        with:
          tools: ${{ steps.toolbox.outputs.tools }}

  actions-lint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Lint GitHub Actions
        uses: ./lint-actions

  go-lint:
    name: Lint Go code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Lint
        uses: ./golangci-lint

  go-test:
    name: Test Go code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Tidy
        run: go mod tidy

      - name: Run install-tools
        run: |
          workdir=$(mktemp -d)
          go build -o "${workdir}/install-tools" ./cmd/install-tools
          jq --raw-output keys[] < toolbox.json | (cd "${workdir}"; xargs ./install-tools)
          export PATH="${workdir}:${PATH}"
          jq --raw-output '.[] | (.postInstall | join(" "))' < toolbox.json | bash -ex

      - name: Run update-internal-actions
        if: github.event_name != 'push'
        run: go run ./hack/go/cmd/update-internal-actions
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run update-toolbox
        run: go run ./hack/go/cmd/update-toolbox
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run wrap-actions
        run: go run ./hack/go/cmd/wrap-actions
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check for uncommitted changes
        uses: ./check-repo-status

  js:
    name: Lint and test JavaScript code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: ./.github/actions/setup-node

      - name: Lint
        run: pnpm run lint
        working-directory: hack/js

      - name: Build
        run: pnpm run build
        working-directory: hack/js

      - name: Check for uncommitted changes
        uses: ./check-repo-status
