name: Update toolbox

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 1

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  update-toolbox:
    name: Update toolbox
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Run update-toolbox
        id: update-toolbox
        run: |
          {
            echo "summary<<EOF"
            go -C hack/go run ./cmd/update-toolbox
            echo "EOF"
          } >> "${GITHUB_OUTPUT}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set up Node.js
        if: steps.update-toolbox.outputs.summary != ''
        uses: ./.github/actions/setup-node

      - name: Build
        if: steps.update-toolbox.outputs.summary != ''
        run: pnpm run build
        working-directory: hack/js

      - name: Generate bot token
        if: steps.update-toolbox.outputs.summary != ''
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: generate-token
        with:
          app-id: ${{ secrets.CERBOS_BOT_CLIENT_ID }}
          private-key: ${{ secrets.CERBOS_BOT_PRIVATE_KEY }}

      - name: Create pull request
        if: steps.update-toolbox.outputs.summary != ''
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update-toolbox
          delete-branch: true
          signoff: true
          sign-commits: true
          author: ${{ vars.CERBOS_BOT_AUTHOR }}
          committer: ${{ vars.CERBOS_BOT_AUTHOR }}
          commit-message: |-
            Update toolbox
          title: |-
            Update toolbox
          body: ${{ steps.update-toolbox.outputs.summary }}
          add-paths: |-
            install-tools/action.mjs
            toolbox.json
